# Generated by Django 5.1.1 on 2024-09-15 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form1',
            fields=[
                ('grant_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('program_title', models.CharField(max_length=255)),
                ('contracting_agency', models.CharField(max_length=255)),
                ('contract_number', models.CharField(blank=True, max_length=100, null=True)),
                ('contract_start_date', models.DateField()),
                ('contract_end_date', models.DateField()),
                ('contract_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('federal_grantor', models.CharField(blank=True, max_length=255, null=True)),
                ('federal_aln', models.CharField(blank=True, max_length=6, null=True)),
                ('internal_award_code', models.IntegerField()),
                ('internal_gl_start_date', models.DateField()),
                ('internal_gl_end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GLExpenditure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('effective_date', models.DateField()),
                ('award_code', models.CharField(max_length=3)),
                ('debit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_expenditure', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fiscal_year', models.CharField(max_length=7)),
                ('expenditure_federal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expenditure_nonfederal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('grant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.form1')),
            ],
        ),
    ]
