# Generated by Django 5.1.1 on 2024-10-07 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form1',
            fields=[
                ('grant_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('program_title', models.CharField(max_length=255)),
                ('contracting_agency', models.CharField(max_length=255)),
                ('contract_number', models.CharField(max_length=50)),
                ('contract_start_date', models.DateTimeField(blank=True, null=True)),
                ('contract_end_date', models.DateTimeField(blank=True, null=True)),
                ('contract_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('federal_grantor', models.CharField(blank=True, max_length=255, null=True)),
                ('federal_aln', models.CharField(blank=True, max_length=255, null=True)),
                ('internal_award_code', models.CharField(max_length=10)),
                ('internal_gl_start_date', models.DateTimeField(blank=True, null=True)),
                ('internal_gl_end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=10)),
            ],
            options={
                'db_table': 'form_1',
            },
        ),
        migrations.CreateModel(
            name='GLExpenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField()),
                ('award_code', models.CharField(max_length=10)),
                ('debit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_expenditure', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fiscal_year', models.CharField(max_length=7)),
                ('grant_id', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'gl_expenditure',
            },
        ),
    ]
