# Generated by Django 5.1.1 on 2024-09-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1',
            name='contract_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='form1',
            name='contract_number',
            field=models.CharField(default='UNKNOWN', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form1',
            name='federal_aln',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='form1',
            name='internal_award_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='glexpenditure',
            name='award_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='glexpenditure',
            name='credit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='glexpenditure',
            name='debit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='glexpenditure',
            name='expenditure_federal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='glexpenditure',
            name='expenditure_nonfederal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='glexpenditure',
            name='grant_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='glexpenditure',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='glexpenditure',
            name='net_expenditure',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterModelTable(
            name='form1',
            table='form_1',
        ),
        migrations.AlterModelTable(
            name='glexpenditure',
            table='gl_expenditure',
        ),
    ]
