# Generated by Django 5.1.1 on 2024-10-14 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(max_length=7)),
                ('federal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nonfederal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.form1')),
            ],
        ),
    ]
