# Generated by Django 5.1.1 on 2024-10-14 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_fiscalbreakdown'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fiscalbreakdown',
            table='fiscal_breakdown',
        ),
    ]
