# Generated by Django 5.1.1 on 2024-09-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_alter_form1_contract_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1',
            name='contract_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='form1',
            name='contract_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='form1',
            name='internal_gl_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='form1',
            name='internal_gl_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
