# Generated by Django 5.1.1 on 2024-10-14 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_alter_fiscalbreakdown_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalbreakdown',
            name='grant_id',
            field=models.ForeignKey(db_column='grant_id', on_delete=django.db.models.deletion.CASCADE, to='tracking.form1'),
        ),
    ]
