# Generated by Django 5.1.1 on 2024-11-08 04:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_alter_fiscalbreakdown_grant_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubsequentAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField()),
                ('award_code', models.CharField(max_length=10)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('net_expenditure', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fiscal_year', models.CharField(max_length=10)),
                ('grant_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.form1')),
            ],
        ),
        migrations.CreateModel(
            name='SubsequentFiscalBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(max_length=10)),
                ('federal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('nonfederal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('grant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.form1')),
            ],
        ),
    ]
