# Generated by Django 5.1.1 on 2024-11-08 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_subsequentadjustment_subsequentfiscalbreakdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsequentadjustment',
            name='grant_id',
            field=models.ForeignKey(blank=True, db_column='grant_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.form1'),
        ),
        migrations.AlterField(
            model_name='subsequentfiscalbreakdown',
            name='grant_id',
            field=models.ForeignKey(db_column='grant_id', on_delete=django.db.models.deletion.CASCADE, to='tracking.form1'),
        ),
    ]
