# Generated by Django 5.1.1 on 2026-07-30 22:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_alter_subsequentadjustment_grant_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1',
            name='federal_aln',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message="Federal ALN must be in the format 'xx.xxx', where x is a digit.", regex='^\\d{2}\\.\\d{3}$')]),
        ),
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant_id', models.CharField(max_length=10)),
                ('request_type', models.CharField(choices=[('NEW_GRANT', 'New Grant'), ('EDIT_GRANT', 'Edit Grant')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RETURNED', 'Returned for Revision'), ('DENIED', 'Denied'), ('APPROVED', 'Approved')], default='PENDING', max_length=20)),
                ('current_revision', models.PositiveIntegerField(default=1)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'change_request',
            },
        ),
        migrations.CreateModel(
            name='ChangeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_no', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note_text', models.TextField(max_length=1000)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_notes', to=settings.AUTH_USER_MODEL)),
                ('change_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='tracking.changerequest')),
            ],
            options={
                'db_table': 'change_note',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChangeAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_no', models.PositiveIntegerField(default=1)),
                ('action', models.CharField(choices=[('APPROVE', 'Approve'), ('RETURN', 'Return for Revision'), ('DENY', 'Deny'), ('RESUBMIT', 'Resubmit')], max_length=10)),
                ('acted_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, default='', max_length=500)),
                ('acted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_actions', to=settings.AUTH_USER_MODEL)),
                ('change_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='tracking.changerequest')),
            ],
            options={
                'db_table': 'change_action',
                'ordering': ['acted_at', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('action', 'APPROVE')), fields=('change_request', 'revision_no', 'acted_by'), name='unique_approval_per_user_per_revision')],
            },
        ),
        migrations.CreateModel(
            name='ChangeRequestField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('revision_no', models.PositiveIntegerField(default=1)),
                ('current_value', models.TextField(blank=True, null=True)),
                ('proposed_value', models.TextField(blank=True, null=True)),
                ('change_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_changes', to='tracking.changerequest')),
            ],
            options={
                'db_table': 'change_request_field',
                'constraints': [models.UniqueConstraint(fields=('change_request', 'revision_no', 'field_name'), name='unique_field_per_request_revision')],
            },
        ),
    ]
