# Generated by Django 5.1.1 on 2026-07-31 21:37

import django.core.validators
import django.db.models.deletion
import tracking.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_add_workflow_models_and_validate_federal_aln'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequest',
            name='grant_id',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Grant ID must contain one capital letter followed by five digits.', regex='^[A-Z]\\d{5}$')]),
        ),
        migrations.AlterField(
            model_name='form1',
            name='grant_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Grant ID must contain one capital letter followed by five digits.', regex='^[A-Z]\\d{5}$')]),
        ),
        migrations.CreateModel(
            name='GrantDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant_id', models.CharField(db_index=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Grant ID must contain one capital letter followed by five digits.', regex='^[A-Z]\\d{5}$')])),
                ('document_type', models.CharField(choices=[('CONTRACT_AMENDMENT', 'Contract/Amendment'), ('CORRESPONDENCE', 'Correspondence')], max_length=25)),
                ('amendment_no', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('correspondence_date', models.DateField(blank=True, null=True)),
                ('correspondence_sequence', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('file', models.FileField(blank=True, max_length=500, upload_to=tracking.models.grant_document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REPLACED', 'Replaced'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('replaced_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('purged_at', models.DateTimeField(blank=True, null=True)),
                ('change_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='tracking.changerequest')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_grant_documents', to=settings.AUTH_USER_MODEL)),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replaced_grant_documents', to=settings.AUTH_USER_MODEL)),
                ('replaces_document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacement_document', to='tracking.grantdocument')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_grant_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'grant_document',
                'ordering': ['grant_id', 'document_type', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='GrantDocumentAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('UPLOAD', 'Upload'), ('EDIT_METADATA', 'Edit Metadata'), ('REPLACE_FILE', 'Replace File'), ('DELETE', 'Delete'), ('PURGE', 'Purge Physical File')], max_length=20)),
                ('acted_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, default='', max_length=500)),
                ('details', models.TextField(blank=True, default='', max_length=1000)),
                ('acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grant_document_actions', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_history', to='tracking.grantdocument')),
            ],
            options={
                'db_table': 'grant_document_action',
                'ordering': ['acted_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='grantdocument',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amendment_no__gte', 0), ('amendment_no__isnull', False), ('amendment_no__lte', 99), ('correspondence_date__isnull', True), ('correspondence_sequence__isnull', True), ('document_type', 'CONTRACT_AMENDMENT')), models.Q(('amendment_no__isnull', True), ('correspondence_date__isnull', False), ('correspondence_sequence__gte', 1), ('correspondence_sequence__isnull', False), ('correspondence_sequence__lte', 99), ('document_type', 'CORRESPONDENCE')), _connector='OR'), name='valid_grant_document_metadata'),
        ),
        migrations.AddConstraint(
            model_name='grantdocument',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('deleted_at__isnull', True), ('deleted_by__isnull', True), ('purged_at__isnull', True), ('replaced_at__isnull', True), ('replaced_by__isnull', True), ('status', 'ACTIVE')), models.Q(('deleted_at__isnull', True), ('deleted_by__isnull', True), ('replaced_at__isnull', False), ('replaced_by__isnull', False), ('status', 'REPLACED')), models.Q(('deleted_at__isnull', False), ('deleted_by__isnull', False), ('replaced_at__isnull', True), ('replaced_by__isnull', True), ('status', 'DELETED')), _connector='OR'), name='valid_grant_document_status_metadata'),
        ),
        migrations.AddConstraint(
            model_name='grantdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('document_type', 'CONTRACT_AMENDMENT'), ('status', 'ACTIVE')), fields=('grant_id', 'amendment_no'), name='unique_active_contract_amendment'),
        ),
        migrations.AddConstraint(
            model_name='grantdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('document_type', 'CORRESPONDENCE'), ('status', 'ACTIVE')), fields=('grant_id', 'correspondence_date', 'correspondence_sequence'), name='unique_active_correspondence'),
        ),
        migrations.AddConstraint(
            model_name='grantdocumentaction',
            constraint=models.CheckConstraint(condition=models.Q(('action', 'PURGE'), ('acted_by__isnull', False), _connector='OR'), name='document_action_actor_required'),
        ),
    ]
