# Generated by Django 5.1.1 on 2026-08-03 21:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_create_user_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='form1',
            name='amendment_no',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='form1',
            name='federal_funding_included',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='form1',
            name='federal_information_status',
            field=models.CharField(blank=True, choices=[('NOT_APPLICABLE', 'Not Applicable — No Federal Funding'), ('PENDING', 'Pending Federal Information'), ('COMPLETE', 'Federal Information Complete'), ('NO_ALN', 'Federal Funding with No ALN')], max_length=20, null=True),
        ),
    ]
