# Generated by Django 5.1.1 on 2026-08-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0012_normalize_federal_placeholder_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='form1',
            name='funding_sources',
            field=models.CharField(blank=True, choices=[('FEDERAL', '100% Federal'), ('NONFEDERAL', '100% Non-federal'), ('BOTH', 'Both Federal and Non-federal'), ('REVIEW_REQUIRED', 'Needs Review — Funding Source Undetermined')], max_length=20, null=True),
        ),
    ]
