# Generated by Django 5.1.1 on 2026-08-10 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0015_classify_funding_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalbreakdown',
            name='reviewed_total_allowed_expenditure',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='subsequentfiscalbreakdown',
            name='reviewed_total_subsequent_adjustment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
