# Generated by Django 5.1.1 on 2026-08-15 20:55

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0017_initialize_allocation_review_snapshots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='form1',
            name='program_income_treatment',
            field=models.CharField(choices=[('NOT_RESEARCHED', 'Not Researched'), ('DEDUCTIVE', 'Deductive'), ('ADDITIVE', 'Additive'), ('COST_SHARING', 'Cost Sharing / Matching'), ('OTHER', 'Other / Contract-Specific Treatment')], default='NOT_RESEARCHED', max_length=20),
        ),
        migrations.CreateModel(
            name='GrantFiscalExceptionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_type', models.CharField(choices=[('NEGATIVE_CONTRACT_BALANCE', 'Negative Contract Balance')], default='NEGATIVE_CONTRACT_BALANCE', max_length=40)),
                ('reviewed_contract_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reviewed_total_allowed_expenditure', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reviewed_program_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reviewed_program_income_treatment', models.CharField(choices=[('NOT_RESEARCHED', 'Not Researched'), ('DEDUCTIVE', 'Deductive'), ('ADDITIVE', 'Additive'), ('COST_SHARING', 'Cost Sharing / Matching'), ('OTHER', 'Other / Contract-Specific Treatment')], max_length=20)),
                ('reviewed_contract_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('explanation', models.TextField()),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accepted_fiscal_exception_reviews', to=settings.AUTH_USER_MODEL)),
                ('grant', models.ForeignKey(db_column='grant_id', on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_exception_reviews', to='tracking.form1')),
            ],
            options={
                'db_table': 'grant_fiscal_exception_review',
                'ordering': ['-accepted_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProgramIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('grant', models.ForeignKey(db_column='grant_id', on_delete=django.db.models.deletion.CASCADE, related_name='program_income_entries', to='tracking.form1')),
            ],
            options={
                'db_table': 'program_income',
                'constraints': [models.UniqueConstraint(fields=('grant', 'fiscal_year'), name='unique_program_income_grant_fiscal_year')],
            },
        ),
    ]
