# Generated by Django 5.1.1 on 2026-08-23 23:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0018_add_program_income_and_fiscal_exception_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='changerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'RETURNED'])), fields=('grant_id',), name='unique_active_change_request_per_grant'),
        ),
    ]
