# Generated by Django 5.1.1 on 2026-08-29 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0019_changerequest_unique_active_change_request_per_grant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinatedChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('RETURNED', 'Returned for Revision'), ('APPLIED', 'Applied'), ('DENIED', 'Denied')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'coordinated_change',
            },
        ),
        migrations.RemoveConstraint(
            model_name='changerequest',
            name='unique_active_change_request_per_grant',
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('RETURNED', 'Returned for Revision'), ('READY', 'Approved - Waiting to Apply'), ('DENIED', 'Denied'), ('APPROVED', 'Approved')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='coordinatedchange',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coordinated_changes_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='coordinated_change',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_requests', to='tracking.coordinatedchange'),
        ),
        migrations.AddConstraint(
            model_name='changerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['DRAFT', 'PENDING', 'RETURNED', 'READY'])), fields=('grant_id',), name='unique_active_change_request_per_grant'),
        ),
    ]
