# Generated by Django 5.1.1 on 2026-08-30 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0020_coordinatedchange_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinatedchange',
            name='cancellation_reason',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='coordinatedchange',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coordinatedchange',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coordinated_changes_cancelled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coordinatedchange',
            name='concurrency_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='coordinatedchange',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coordinated_changes_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coordinatedchange',
            name='withdrawal_reason',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='coordinatedchange',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coordinatedchange',
            name='withdrawn_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coordinated_changes_withdrawn', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='changeaction',
            name='action',
            field=models.CharField(choices=[('APPROVE', 'Approve'), ('RETURN', 'Return for Revision'), ('DENY', 'Deny'), ('RESUBMIT', 'Resubmit'), ('WITHDRAW', 'Withdraw')], max_length=10),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('RETURNED', 'Returned for Revision'), ('READY', 'Approved - Waiting to Apply'), ('DENIED', 'Denied'), ('APPROVED', 'Approved'), ('CANCELLED', 'Cancelled'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_change_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coordinatedchange',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('RETURNED', 'Returned for Revision'), ('APPLIED', 'Applied'), ('DENIED', 'Denied'), ('CANCELLED', 'Cancelled'), ('WITHDRAWN', 'Withdrawn')], default='DRAFT', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='changerequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'DRAFT'), _negated=True), ('coordinated_change__isnull', False), _connector='OR'), name='draft_request_requires_coordinated_change'),
        ),
    ]
