# Generated by Django 5.1.1 on 2026-09-06 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0021_coordinatedchange_cancellation_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRequestIntegrityIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_no', models.PositiveIntegerField()),
                ('request_status_at_detection', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('RETURNED', 'Returned for Revision'), ('READY', 'Approved - Waiting to Apply'), ('DENIED', 'Denied'), ('APPROVED', 'Approved'), ('CANCELLED', 'Cancelled'), ('WITHDRAWN', 'Withdrawn')], max_length=20)),
                ('detected_during', models.CharField(choices=[('APPROVAL', 'Approval'), ('RETURN', 'Return for Revision'), ('RESUBMIT', 'Resubmission'), ('REVIEW', 'Review'), ('OTHER', 'Other')], max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('classification', models.CharField(blank=True, choices=[('LEGITIMATE', 'Legitimate'), ('ILLEGITIMATE', 'Illegitimate')], max_length=20, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_comment', models.TextField(blank=True, default='', max_length=1000)),
                ('change_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integrity_issues', to='tracking.changerequest')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_change_request_integrity_issues', to=settings.AUTH_USER_MODEL)),
                ('detected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detected_change_request_integrity_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'change_request_integrity_issue',
                'ordering': ['-detected_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ChangeRequestIntegritySnapshotField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('DETECTION', 'Detection'), ('DISPOSITION', 'Disposition')], max_length=20)),
                ('field_name', models.CharField(max_length=100)),
                ('authoritative_value', models.TextField(blank=True, default='')),
                ('integrity_issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshot_fields', to='tracking.changerequestintegrityissue')),
            ],
            options={
                'db_table': 'change_request_integrity_snapshot_field',
                'ordering': ['stage', 'field_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='changerequestintegrityissue',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('change_request',), name='unique_open_integrity_issue_per_request'),
        ),
        migrations.AddConstraint(
            model_name='changerequestintegrityissue',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('classification__isnull', True), ('closed_at__isnull', True), ('closed_by__isnull', True), ('status', 'OPEN')), models.Q(('classification__isnull', False), ('closed_at__isnull', False), ('closed_by__isnull', False), ('status', 'CLOSED')), _connector='OR'), name='integrity_issue_close_fields_consistent'),
        ),
        migrations.AddConstraint(
            model_name='changerequestintegritysnapshotfield',
            constraint=models.UniqueConstraint(fields=('integrity_issue', 'stage', 'field_name'), name='unique_integrity_snapshot_field_per_stage'),
        ),
    ]
