# Generated by Django 5.1.1 on 2026-09-08 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0022_changerequestintegrityissue_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinatedchange',
            name='current_revision',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='CoordinatedChangeAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_no', models.PositiveIntegerField(default=1)),
                ('action', models.CharField(choices=[('APPROVE', 'Approve'), ('RETURN', 'Return for Revision'), ('DENY', 'Deny'), ('RESUBMIT', 'Resubmit')], max_length=10)),
                ('acted_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, default='', max_length=500)),
                ('acted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coordinated_change_actions', to=settings.AUTH_USER_MODEL)),
                ('coordinated_change', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='tracking.coordinatedchange')),
            ],
            options={
                'db_table': 'coordinated_change_action',
                'ordering': ['acted_at', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('action', 'APPROVE')), fields=('coordinated_change', 'revision_no', 'acted_by'), name='unique_coordinated_approval_per_user_per_revision')],
            },
        ),
    ]
