# Generated by Django 5.1.1 on 2026-10-06 04:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0023_coordinatedchange_current_revision_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='changerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('request_type', 'NEW_GRANT')), fields=('grant_id',), name='unique_new_grant_request_per_grant_id'),
        ),
    ]
